### ISSUE TITLE
TTS should not interrupt itself

### ISSUE THREAD

**Issue by fcnjd** [scheibler/WalkersGuide-Android#6]
Hi,
when walking a route, it can happen that distance interval announcements interrupt the routing announcements. A lower interval has the advantage of a higher precision during the walk - while this increases the risk of suppressing an ongoing announcement spoken when the next route point is reached.
To fix this, an announcement should lock the TTS service as long as it is speaking, and when finish release it for the next one in queue to get spoken.

**Comment by scheibler** [comment]
Yes, I agree. I encountered the same problem and it's already on my ToDo list.

**Comment by fcnjd** [comment]
Great, that's good to know. Sorry for creating that issue then, I didn't know you already have a todo for that.

**Comment by scheibler** [comment]
At last I found the time to implement a message queue for tts announcements. For example distance
messages get queued behind navigation instructions now. Furthermore Talkback does not longer
interrupt if the distance label is focused. You also can adjust the speech rate of the tts now. It
can be found in the app settings.

You can either download the .apk file for the test version or build the app yourself from the develop branch.
Link: https://www.walkersguide.org/downloads/WalkersGuide-prod-3.2.0-b5-release.apk

**Comment by scheibler** [comment]
See release v3.2.0
