### ISSUE TITLE
android-rocket-launcher cannot be resolved during build

### ISSUE THREAD

**Issue by fcnjd** [scheibler/WalkersGuide-Android#7]
When trying to build the project using gradle, the following error occurs:
A problem occurred configuring root project 'WalkersGuide'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.cesarferreira:android-rocket-launcher:1.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/cesarferreira/android-rocket-launcher/1.0.0/android-rocket-launcher
-1.0.0.pom
       - https://jcenter.bintray.com/com/cesarferreira/android-rocket-launcher/1.0.0/android-rocket-launcher-1.0.0.pom
     Required by:
         project :

I ran the command `./gradlew build`. My environment:
julian@server1:~/src/WalkersGuide-Android$ ./gradlew --version

------------------------------------------------------------
Gradle 8.3
------------------------------------------------------------

Build time:   2023-08-17 07:06:47 UTC
Revision:     8afbf24b469158b714b36e84c6f4d4976c86fcd5

Kotlin:       1.9.0
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.12 (Debian 17.0.12+7-Debian-2deb12u1)
OS:           Linux 6.1.0-25-cloud-amd64 amd64

**Comment by scheibler** [comment]
That's a helper to open the app directly from the command line[1]. It just adds a gradle task. It
should be resolved by the jcenter repository which provides older packages. But it seems that this no
longer works.

If you don't need it just comment out the respective line:

    dependencies {
        // classpath 'com.cesarferreira:android-rocket-launcher:1.0.0'
    }

in the top-level build.gradle file.

1: https://github.com/cesarferreira/android-rocket-launcher
